//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Triamec.Tam.Samples.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GearUp.TAMcfg")]
        public string TamConfigurationPath {
            get {
                return ((string)(this["TamConfigurationPath"]));
            }
            set {
                this["TamConfigurationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29")]
        public global::Triamec.TriaLink.UniqueDeviceId SerialNumberMaster {
            get {
                return ((global::Triamec.TriaLink.UniqueDeviceId)(this["SerialNumberMaster"]));
            }
            set {
                this["SerialNumberMaster"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public global::Triamec.TriaLink.UniqueDeviceId SerialNumberSlave {
            get {
                return ((global::Triamec.TriaLink.UniqueDeviceId)(this["SerialNumberSlave"]));
            }
            set {
                this["SerialNumberSlave"] = value;
            }
        }
    }
}
